# Generated by Django 5.1.3 on 2024-12-09 16:27

import core.utils
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=core.utils.profile_image_thumbnail),
        ),
    ]
