# Generated by Django 3.2.9 on 2021-11-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_seeker_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
    ]
