# Generated by Django 3.2.9 on 2021-11-14 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('jobs', '0003_remove_company_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('current_role', models.CharField(blank=True, max_length=100)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='seeker',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seekers', to='jobs.job'),
            preserve_default=False,
        ),
    ]
