# Generated by Django 3.2.9 on 2021-11-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20211114_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
