# Generated by Django 3.2.9 on 2021-12-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='requirements',
            new_name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_applicant',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
