# Generated by Django 3.2.9 on 2021-12-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20211221_0117'),
        ('jobs', '0006_auto_20211216_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile'),
        ),
    ]
