# Generated by Django 3.2.9 on 2022-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='current_role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
