# Generated by Django 3.2.9 on 2022-01-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
