# Generated by Django 3.2.9 on 2022-01-15 15:05

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_seeker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.transcript_thumbnail),
        ),
    ]
