# Generated by Django 3.2.9 on 2022-01-17 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_seeker_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
