# Generated by Django 5.1.3 on 2024-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salaryTo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
