# Generated by Django 3.2.9 on 2021-12-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_company'),
        ('company', '0002_auto_20211221_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
