# Generated by Django 3.2.9 on 2021-12-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='values',
            new_name='val',
        ),
    ]
