# Generated by Django 3.2.9 on 2022-01-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofileimages',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
