# Generated by Django 5.1.3 on 2024-12-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyprofileimages_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='num_of_employees',
            field=models.CharField(blank=True, null=True),
        ),
    ]
